version: '3.9'
services:
  web:
    expose:
      - 3000
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.staging_web.rule=Host(`dev.cyberdas.net`)

networks:
  proxy:
    external: true
