version: '3.9'
services:
    main:
        build:
            context: .
            dockerfile: Dockerfile.main
        ports:
            - '${MAIN_PORT}:3000'
    storybook:
        build:
            context: .
            dockerfile: Dockerfile.storybook
        ports:
            - '${STORYBOOK_PORT}:3001'
