name: Build and Deploy (staging)

on:
    push:
        branches: [ main ]

jobs:
    deploy:
        runs-on: [self-hosted, linux, X64]
        env:
            COMPOSE_FILE: docker-compose.yml:docker-compose.production.yml
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  path: dev 
            - name: Create dotenv file
              working-directory: dev
              run: |
                  touch .env
            - name: Build container
              working-directory: dev
              run: |
                  docker-compose build web
            - name: Deploy container
              working-directory: dev
              run: |
                  docker-compose up --no-deps -d web
            - name: Check that container is running
              working-directory: dev
              run: |
                  if [ "$(docker container inspect -f '{{.State.Status}}' $(docker-compose ps -q))" != "running" ]; then
                    exit 1 
                  fi
            