name: deploy-dev

on:
    push:
        branches: [ main ]

jobs:
    deploy:
        runs-on: [self-hosted, linux, X64]
        env:
            MAIN_PORT: 4000
            STORYBOOK_PORT: 4001
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  path: dev  
            - name: Docker compose
              working-directory: dev
              run: |
                  docker-compose up -d --build