name: deploy-prod

on:
    release:
        branches: [ main ]
        types: [ released, deleted ]

jobs:
    update:
        runs-on: [self-hosted, linux, X64]
        steps:
            - name: Get latest released version
              id: lastver
              uses: pozetroninc/github-action-get-latest-release@v0.5.0
              with:
                  repository: ${{ github.repository }}
                  excludes: prerelease, draft
            - name: Checkout latest tag
              uses: actions/checkout@v2
              with:
                  ref: ${{ steps.lastver.outputs.release }}
                  path: prod
            - name: Install dependencies
              working-directory: prod
              run: |
                  npm ci

    deploy:
        needs: update
        runs-on: [self-hosted, linux, X64]
        env:
            REACT_APP_YM_ID: ${{ secrets.YM_ID }}
            REACT_APP_GA_ID: ${{ secrets.GA_ID }}
        steps:
            - name: Set production API
              working-directory: prod/src/API
              run: |
                  python3 -c "with open('http.js', 'r+') as f:
                      d = f.read()
                      d = d.replace('https://api.cyberdas.net/next', 'https://api.cyberdas.net/v1')
                      f.seek(0)
                      f.write(d)
                      f.truncate()
                      f.close()"
            - name: Build
              working-directory: prod
              run: |
                  npm run build
            - name: Transfer new version to web-server
              working-directory: prod
              run: |
                  rm -rf /var/www/html/*  
                  cp -r build/. /var/www/html/

    deploy-storybook:
        needs: update
        runs-on: [self-hosted, linux, X64]
        steps:
            - name: Build
              working-directory: prod
              run: |
                  npm run build-storybook
            - name: Transfer new version to web-server
              working-directory: prod
              run: |
                  rm -rf /var/www/storybook/main/*  
                  cp -r storybook-static/. /var/www/storybook/main/
