name: Build and Deploy (staging)

on:
    push:
        branches: [ main ]

jobs:
    checkout:
        runs-on: [self-hosted, linux, X64]
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  path: dev  

    deploy:
        needs: checkout
        runs-on: [self-hosted, linux, X64]
        steps:
            - name: Create dotenv file
              working-directory: dev
              run: |
                  touch .env
            - name: Build container
              working-directory: dev
              run: |
                  docker-compose -f docker-compose.yml -f docker-compose.production.yml build web
            - name: Deploy container
              working-directory: dev
              run: |
                  docker-compose -f docker-compose.yml -f docker-compose.production.yml up --no-deps -d web
            
    healthcheck:
        needs: deploy
        runs-on: [self-hosted, linux, X64]
        steps:
            - name: Get container id
              working-directory: dev
              id: contid 
              run: |
                  docker-compose -f docker-compose.yml -f docker-compose.production.yml ps -q
            - name: Check container status
              id: contstatus
              run: |
                  docker container inspect -f '{{.State.Status}}' ${{ steps.contid.outputs }}
            - name: Exit on error
              if: steps.contstatus.outputs != 'running'
              run: exit 1
            