name: deploy-prod

on:
    push:
        branches: [main]

jobs:
    update:
        runs-on: [self-hosted, linux, X64]
        defaults:
            run:
                working-directory: /usr/share/cyberdas_front
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  path: prod
            - name: Install dependencies
              working-directory: prod
              run: |
                  npm ci

    deploy:
        needs: update
        runs-on: [self-hosted, linux, X64]
        steps:
            - name: Build
              working-directory: prod
              run: |
                  npm run build
            - name: Transfer new version to web-server
              working-directory: prod
              run: |
                  rm -rf /var/www/html/*  
                  cp -r build/. /var/www/html/

    deploy-storybook:
        needs: update
        runs-on: [self-hosted, linux, X64]
        steps:
            - name: Build
              working-directory: prod
              run: |
                  npm run build-storybook
            - name: Transfer new version to web-server
              working-directory: prod
              run: |
                  rm -rf /var/www/storybook/main/*  
                  cp -r storybook-static/. /var/www/storybook/main/