name: Build and Deploy (production)

on:
    release:
        branches: [ main ]
        types: [ released, deleted ]

jobs:
    deploy:
        runs-on: [self-hosted, linux, X64]
        env:
            COMPOSE_FILE: docker-compose.yml:docker-compose.production.yml
            DOTENV_NEXT_PUBLIC_YM_ID: ${{ secrets.YM_ID }}
            DOTENV_NEXT_PUBLIC_GA_ID: ${{ secrets.GA_ID }}
            DOTENV_GENERATE_SOURCEMAP: false
        steps:
            - name: Get latest released version
              id: lastver
              uses: pozetroninc/github-action-get-latest-release@v0.5.0
              with:
                  repository: ${{ github.repository }}
                  excludes: prerelease, draft
            - name: Checkout latest tag
              uses: actions/checkout@v2
              with:
                  ref: ${{ steps.lastver.outputs.release }}
                  path: prod
            - name: Set production API
              working-directory: prod/src/API
              run: |
                  python3 -c "with open('http.js', 'r+') as f:
                      d = f.read()
                      d = d.replace('https://api.cyberdas.net/next', 'https://api.cyberdas.net/v1')
                      f.seek(0)
                      f.write(d)
                      f.truncate()
                      f.close()"
            - name: Create dotenv file
              uses: iamsauravsharma/create-dotenv@v1.2.0
              with:
                  env-prefix: 'DOTENV_'
                  directory: 'prod/'
            - name: Build container
              working-directory: prod
              run: |
                  docker-compose build web
            - name: Deploy container
              working-directory: prod
              run: |
                  docker-compose up --no-deps -d web
            - name: Check that container is running
              working-directory: prod
              run: |
                  if [ "$(docker container inspect -f '{{.State.Status}}' $(docker-compose ps -q))" != "running" ]; then
                    exit 1 
                  fi