name: Build and Deploy (staging)

on:
    push:
        branches: [ main ]

jobs:
    deploy:
        runs-on: [self-hosted, linux, X64]
        env:
            COMPOSE_FILE: docker-compose.yml:docker-compose.staging.yml
        steps:
            - name: Save old image ID
              id: old_image
              working-directory: dev
              run: |
                  echo "::set-output name=id::$(docker-compose images -q web)"
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  path: dev
            - name: Build container
              working-directory: dev
              run: |
                  docker build -t cyberdas_web:${{ github.sha }} .
            - name: Start container
              id: new_container
              run: |
                  echo "::set-output name=id::$(docker run -d cyberdas_web:${{ github.sha }})" 
            - name: Validate that container is able to run
              run: |
                  if [ "$(docker container inspect -f '{{.State.Status}}' ${{ steps.new_container.outputs.id }})" != "running" ]; then
                    docker stop ${{ steps.new_container.outputs.id }}
                    docker rm ${{ steps.new_container.outputs.id }}
                    docker image rm cyberdas_web:${{ github.sha }}
                    exit 1 
                  fi
            - name: Deploy container
              working-directory: dev
              run: |
                  TAG=${{ github.sha }} docker-compose up -d web
            - name: Remove old image
              run: |
                  docker image rm ${{ steps.old_image.outputs.id }}
              continue-on-error: true
            