name: run-tests

on:
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: [self-hosted, linux, X64]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: test
      - name: Install dependencies
        working-directory: test
        run: |
          npm ci

  test:
    needs: build
    runs-on: [self-hosted, linux, X64]
    steps:
      - name: Run linter
        working-directory: test
        run: |
          npx eslint --max-warnings 0 src 
      - name: Wipe files
        run: |
          rm -rf test
