name: run-tests

on:
    pull_request:
        branches: [ main ]

jobs:
    build:
        runs-on: [self-hosted, linux, X64]
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  path: test
            - name: Install dependencies
              working-directory: test
              run: |
                  npm ci

    test:
        needs: build
        runs-on: [self-hosted, linux, X64]
        steps:
            - name: Run code linter
              working-directory: test
              run: |
                  npm run lint:code
            - name: Run style linter
              working-directory: test
              run: |
                  npm run lint:style
            - name: Run tests
              working-directory: test
              run: |
                  npm test
            - name: Wipe files
              run: |
                  rm -rf test
