name: Execute tests

on:
    pull_request:
        branches: [ main ]

jobs:
    test:
        runs-on: [self-hosted, linux, X64]
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  path: test-${{ github.sha }}
            - name: Build and start container
              working-directory: test-${{ github.sha }}
              run: |
                  docker build -t web-test:${{ github.sha }} --target test .
            - name: Run tests
              working-directory: test-${{ github.sha }}
              run: |
                  docker run --rm --name web-test web-test:${{ github.sha }}
            - name: Shutdown container
              if: ${{ always() }}
              working-directory: test-${{ github.sha }}
              run: |
                  docker image rm web-test:${{ github.sha }}
            - name: Wipe files
              if: ${{ always() }}
              run: |
                  rm -rf test-${{ github.sha }}
