name: Execute tests

on:
    pull_request:
        branches: [ main ]

jobs:
    build:
        needs: checkout
        runs-on: [self-hosted, linux, X64]
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  path: test
            - name: Build and start container
              working-directory: test
              run: |
                  docker-compose -f docker-compose.yml up -d --build web

    test:
        needs: build
        runs-on: [self-hosted, linux, X64]
        steps:
            - name: Run tests
              working-directory: test
              run: |
                  docker-compose -f docker-compose.yml exec -T web sh /app/scripts/test.sh
            - name: Shutdown container
              working-directory: test
              run: |
                  docker-compose -f docker-compose.yml down --remove-orphans
            - name: Wipe files
              run: |
                  rm -rf test
