name: run-tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    # Все пуши, попадающие в эти ветки, должны быть уже протестированы

jobs:

  build:
    runs-on: [self-hosted, linux, X64]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: test
      - name: Install dependencies
        working-directory: test
        run: |
          npm ci

  test:
    needs: build
    runs-on: [self-hosted, linux, X64]
    steps:
      - name: Run linter
        working-directory: test
        run: |
          ./node_modules/.bin/eslint --max-warnings 0 src 
      - name: Wipe files
        run: |
          rm -rf test